config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :recipe_foods, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  resources :recipe_items
  resources :foods
  resources :users
  get '/public_recipes', to: 'recipe_items#public_recipes'
  get '/general_shopping_lists', to: 'recipe_foods#general_shopping_lists'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe_item.rb
class RecipeItem < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, :preparation_time, :cooking_time, :description, presence: true

  def total_cost
    total = 0

    recipe_foods.includes(:food).each do |recipe_food|
      total += recipe_food.quantity * recipe_food.food.price
    end

    total.round(2)
  end
end

app/controllers/recipe_items_controller.rb
class RecipeItemsController < ApplicationController
  before_action :set_recipe_item, only: %i[show edit update destroy]

  # GET /recipe_items or /recipe_items.json
  def index
    @recipe_items = RecipeItem.all
  end

  # GET /recipe_items/1 or /recipe_items/1.json
  def show
    @food = Food.all
    @recipe_food = RecipeFood.includes(:food)
  end

  # GET /recipe_items/new
  def new
    @recipe_item = RecipeItem.new
  end

  def public_recipes
    @recipes = RecipeItem.includes(:user).where(public: true).order(created_at: :desc)
    @recipe_food = RecipeFood.all
  end

  # GET /recipe_items/1/edit
  def edit; end

  # POST /recipe_items or /recipe_items.json
  def create
    @recipe_item = RecipeItem.new(recipe_item_params)
    @recipe_item.user_id = current_user.id

    respond_to do |format|
      if @recipe_item.save
        format.html { redirect_to recipe_item_url(@recipe_item), notice: 'Recipe item was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_items/1 or /recipe_items/1.json
  def update
    respond_to do |format|
      if @recipe_item.update(recipe_item_params)
        format.html { redirect_to recipe_item_url(@recipe_item), notice: 'Recipe item was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_items/1 or /recipe_items/1.json
  def destroy
    @recipe_item.destroy

    respond_to do |format|
      format.html { redirect_to recipe_items_url, notice: 'Recipe item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_item
    @recipe_item = RecipeItem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_item_params
    params.require(:recipe_item).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/helpers/recipe_items_helper.rb
module RecipeItemsHelper
end

app/views/recipe_items/_form.html.erb
<%= form_with(model: recipe_item) do |form| %>
  <% if recipe_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_item.errors.count, "error") %> prohibited this recipe_item from being saved:</h2>

      <ul>
        <% recipe_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field :preparation_time %>
  </div>

  <div class="field">
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.number_field :cooking_time %>
  </div>

  <div class="field">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="public">
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div class="update">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_items/_recipe_item.html.erb
<div id="recipe-details">
  <div>
    <p>
      <strong>Name:</strong>
      <%= recipe_item.name %>
    </p>

    <p>
      <strong>Preparation time:</strong>
      <%= recipe_item.preparation_time %>hrs
    </p>

    <p>
      <strong>Cooking time:</strong>
      <%= recipe_item.cooking_time %>hrs
    </p>

    <p>
      <strong>Follow these steps:</strong>
      <%= recipe_item.description %>
    </p>
  </div>

  <div>
    <p> <strong>public:</strong>
      <input type="checkbox" <%= 'checked' if recipe_item.public %> disabled>
    </p>
  </div>


</div>

app/views/recipe_items/edit.html.erb
<div class= "edit-recipe">
  <h2 class= "Edit-header">Editing recipe item</h2>

  <%= render "form", recipe_item: @recipe_item %>

  <br>

  <div>
    <%= link_to "Show this recipe item", @recipe_item %> |
    <%= link_to "Back to recipe items", recipe_items_path %>
  </div>
</div>

app/views/recipe_items/index.html.erb
<h1 class="food_title">Recipe items</h1>

<div id="recipe_items">
  <% @recipe_items.each do |recipe_item| %>
    <div class= "card-container">
      <div class= "card-header">
        <h3>Recipe <%= recipe_item.id%></h3>
        <h2><%= link_to recipe_item.name, recipe_item%></h2>
        <div class= "view-delete">        
          <div>
            <p>
              <%= link_to "View", recipe_item %>
            </p>
          </div>
          <% if can? :delete, recipe_item %>
          <div>
            <%= button_to "Delete", recipe_item, method: :delete, class: "delete" %>
          </div>
          <%end%>
        </div>
      </div>
      <div class= "description">
        <h4>Description:</h4>
        <p><%=recipe_item.description %></p>
      </div>
    </div>

  <% end %>
</div>

<%= link_to "Add new recipe", new_recipe_item_path, class: "btn_new_food" %>

app/views/recipe_items/new.html.erb
<h1>New recipe item</h1>

<%= render "form", recipe_item: @recipe_item %>

<br>

<div>
  <%= link_to "Back to recipe items", recipe_items_path %>
</div>

app/views/recipe_items/public_recipes.html.erb
<h1 class="food_title">Public Recipes</h1> </br>

<% @recipes.each do |recipe| %>
  <%= link_to recipe_item_path(recipe.id), class:"public_recipes" do %> 
    <ul class="recipe_name">
    <li><%= recipe.name %></li>
    <li>by <%= recipe.user.name %></li>
    </ul>
    <ul class="recipe_total">
    <li>Total food items: <%= recipe.recipe_foods.count %></li>
    <li>Total price: $<%= recipe.total_cost %></li>
    </ul>
  <% end %>
  <% end %>

app/views/recipe_items/show.html.erb
<h2 class="food_title">Recipe <%= @recipe_item.id%> </h2>
<%= render @recipe_item %>

<div class= "recipe-link">
<%= link_to "Generate shopping list", general_shopping_lists_path%>
<% if can? :delete, @recipe_item %>
  <%= link_to "Add new ingredient", new_recipe_food_path%>
<%end%>
</div>

<table id="foods">
  <tr class= "table-heading">
    <th>Food</th>
    <th>Quantity</th>
    <th>Value</th>
    <% if can? :delete, @recipe_item %>
    <th>Actions</th>
    <%end%>
  </tr>
  <% @recipe_food.each do |item|%>
    <%if @recipe_item.id == item.recipe_item_id%>
      <tr id="<%= dom_id item %>">
        <td class="table_data"><%= item.food.name %></td>
        <td class="table_data"><%= item.quantity%><%= item.food.measurement_unit%></td>
        <td class="table_data">$<%= item.quantity * item.food.price%></td>
        <% if can? :delete, @recipe_item %>
          <td class="table_data modify"><%= button_to "Delete", item, method: :delete, class: "btn_delete" %><%= link_to "Modify", edit_recipe_food_path, class: "btn_delete" %></td>
        <%end%>
      </tr>
    <%end%>
  <%end%>
</table>

<div class= "links">
  <% if can? :delete, @recipe_item %>
    <%= link_to "Edit", edit_recipe_item_path(@recipe_item), class: "delete" %> 

    <%= button_to "Delete", @recipe_item, method: :delete, class: "delete" %>
  <%end%>
  <%= link_to "Go Back", recipe_items_path, class: "delete" %>
</div>