config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :recipe_foods, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  resources :recipe_items
  resources :foods
  resources :users
  get '/public_recipes', to: 'recipe_items#public_recipes'
  get '/general_shopping_lists', to: 'recipe_foods#general_shopping_lists'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe_item
  belongs_to :food

  validates :quantity, presence: true
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]

  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = RecipeFood.all
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  def show; end

  # GET /recipe_foods/new
  def new
    @recipe_food = RecipeFood.new
    @foods = Food.all
    @recipe_items = RecipeItem.all
  end

  def general_shopping_lists
    @recipe_foods = RecipeFood.includes(:food)
    @food_count = RecipeFood.select(:food_id).distinct.count
  end

  # GET /recipe_foods/1/edit
  def edit; end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = RecipeFood.new(recipe_food_params)

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_items_url, notice: 'Recipe food was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_foods/1 or /recipe_foods/1.json
  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_food_url(@recipe_food), notice: 'Recipe food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_item_url, notice: 'Recipe food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:recipe_item_id, :food_id, :quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipe_item_id, style: "display: block", class: "label" %>
    <%= form.select :recipe_item_id, @recipe_items.map { |recipe_item| [recipe_item.name, recipe_item.id] } %>
  </div>

  <div class="field">
    <%= form.label :food_id, style: "display: block", class: "label" %>
    <%= form.select :food_id, @foods.map { |food| [food.name, food.id] } %>
  </div>

  <div class="field">
    <%= form.label :quantity, style: "display: block", class: "label" %>
    <%= form.number_field :quantity, required: true, class:"input" %>
  </div>

  <div>
    <%= form.submit class: "btn-submit" %>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Recipe item:</strong>
    <%= recipe_food.recipe_item_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

</div>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Show this recipe food", @recipe_food %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>
</div>

app/views/recipe_foods/general_shopping_lists.html.erb
<h1 class="food_title">Shopping List</h1>

<div class="sum_amount">
<p>Amount of food items to buy: <%= @food_count %> </p>
<% food_quantities_prices = @recipe_foods.map { |food| food.quantity * food.food.price } %>
<p>Total value of food needed: <%= number_to_currency(food_quantities_prices.sum) %> </p>

</div> </br>

<table id="foods">
  <tr>
    <th>Name</th>
    <th>Quantity</th>
    <th>Price</th>
    </tr>
    <% @recipe_foods.group_by{|food| food.food.name}.each do |name, foods| %>
    <tr>
      <td class="table_data"><%= name %></td>
      <td class="table_data"><%= foods.sum(&:quantity) %></td>
      <td class="table_data"><%= number_to_currency(foods.first.food.price * foods.sum(&:quantity))%></td>
    </tr>
  <% end %>
  </table>

app/views/recipe_foods/index.html.erb
<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1 class="food_title">New recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Back to recipe foods", recipe_foods_path %>
</div>

app/views/recipe_foods/show.html.erb
<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>