config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :recipe_foods, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  resources :recipe_items
  resources :foods
  resources :users
  get '/public_recipes', to: 'recipe_items#public_recipes'
  get '/general_shopping_lists', to: 'recipe_foods#general_shopping_lists'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar.html.erb
<header>
    <nav>
        <ul class="nav_list">
            <button class="hamburger-btn">
                <span class="hamburger-icon">
                <li class="menu"></li>
                <li class="menu"></li>
                <li class="menu"></li>
                </span>
            </button>
            <li><%= link_to "Recipe App", root_path, class: "nav-title" %></li>
            <li class="nav_items">
            <button class="close-btn">
               <span class="close-icon">X</span>
            </button>
            <%= link_to "Home", root_path, class: "nav-item mobile-home" %>
            <%= link_to "Foods", foods_path, class: "nav-item" %>
            <%= link_to "Recipes", recipe_items_path, class: "nav-item" %>
            <%= link_to "Public Recipes", public_recipes_path, class: "nav-item" %>
            <%= link_to "Shopping List", general_shopping_lists_path, class: "nav-item" %>
            </li>
            <% if user_signed_in? %>
            <li class="sign_out">
            <p class="nav_name">Hey <%= current_user.name%></p>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-btn"%>
            </li>
            <% else %>
            <li><%= button_to "Sign In", new_user_session_path, class: "nav-btn"  %></li>
            <% end %>
        </ul>
    </nav>
</header>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Philosopher:ital,wght@0,400;0,700;1,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", async: true %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>